flasc/visualization.py
Add a feature that allows users to easily plot timeseries data that wraps around 0/360 deg (or 0/2 pi) without the erroneous vertical lines crossing the plot. Here is an example with a sinusoidal signal, wrapping around 0 and 360 deg:
```
y = 180.0 + 200.0 * np.sin(np.linspace(0.0, 10.0, 50))
y = np.remainder(y, 360.0)
t = np.arange(len(y))
fig, ax = plt.subplots()
ax.plot(t, y, color="gray", label="Raw")
ax.grid(True)
ax.set_xlabel("Time")
ax.set_ylabel("Wind direction (deg)")
plot_with_wrapping(t, y, ax=ax, high=360.0, color="orange", marker="o", label="Wrapped")
ax.legend()
ax.set_ylim([0, 360.0])
plt.show()
```
By accounting for wrapping, we can prevent sharp vertical lines that incorrectly connect data points that wrap around 360 deg.
=> Add feature to plot data with angle wrapping

flasc/floris_tools.py, flasc/visualization.py
Issue #12 demonstrates that `calc_floris_approx_table` in floris_tools currently fails when no value for `ti_array` is specified. Problem can be reproduced by:
```
import os
from floris.tools.floris_interface import FlorisInterface
from flasc import floris_tools as ftls
if __name__ == "__main__":
file_path = os.path.dirname(os.path.abspath(__file__))
fi_path = os.path.join(file_path, "demo_floris_input.yaml")
fi = FlorisInterface(fi_path)
df_approx = ftls.calc_floris_approx_table(fi)
print(df_approx)
```
and yields the error:
```
Exception has occurred: AxisError
axis -1 is out of bounds for array of dimension 0
File "/home/bartdoekemeijer/python_scripts/flasc/flasc/floris_tools.py", line 406, in calc_floris_approx_table
ti_array = np.sort(ti_array)
File …
```
=> Bugfix: Add default for ti_array in calc_floris_approx_table

flasc/optimization.py
Issue #11 demonstrates an inconsistency and error in the examples when comparing `pd.Timestamp` variables with `np.datetime64`. @ChristianBurth explains in #11 that
>  pd.Timestamp objects generally have a reference to a timezone, while np.datetime64 objects do not.
Hence, we resolve this by converting `pd.Timestamp` objects to `np.datetime64` prior to comparing the variables.
=> Bugfix: Deal with inconsistent pd.datetime and np.datetime64 formats

flasc/dataframe_operations/dataframe_filtering.py
Is ready to merge
Working on a project recently I had a strange issue where the year/week assignments plot_highlight_data_by_conds would get scrambled.  Posting the question to stack overflow:
https://stackoverflow.com/questions/73911825/how-does-datetime-understand-53rd-week/73912659#73912659
The resolution seems to be a deprecation of .week in favor of .isocalendar().week, so made that change here (don't see any other calls to .week in flasc currently)
This resolves the scrambling issue in my test, and you can see also the improvement in the little demo shown on stack link above.
Finally merging to core.base because I got somehow lapped and have those changes in my local develop.  Hopefully getting these things all merged up will untie some …
=> Use isocalendar() to avoid error in year/week

examples/_legacy/sensitivity_analysis/simple_sobol_example.py, flasc/dataframe_operations/dataframe_filtering.py, flasc/energy_ratio/energy_ratio.py, flasc/energy_ratio/energy_ratio_suite.py, flasc/floris_tools.py, flasc/model_estimation/floris_sensitivity_analysis.py, flasc/optimization.py, requirements.txt, setup.py, tests/optimization_test.py
I believe ready to be merged
I recently had an error that the DataError class was not a member of core.base and found it instead in pandas.errors, maybe this is just something that changed in pandas versions?  I'm running 1.4.4
@Bartdoekemeijer  does this change make any trouble for you?
=> change DataError from core.base to pandas.errors

flasc/energy_ratio/energy_ratio.py, flasc/energy_ratio/energy_ratio_suite.py, flasc/energy_ratio/energy_ratio_visualization.py
Is ready to be merged
Make labeling UQ optional in energy ratio plot, with default set to False 
Issue #29
=> Make labeling UQ optional in energy ratio plot

.github/workflows/continuous-integration-workflow.yaml
I think yes
Very small change to get codecov failure to knock it off
Issue #42
=> update codecov version

flasc/time_operations.py, tests/df_time_operations_test.py
Recent updates to `df_downsample()` (in time_operations.py) removed functionality for providing information about which indices from the full resolution dataframe went into each index of the downsampled dataframe. This broke some functionality for some users. 
This bugfix addresses this issue by reinstating the `return_index_mapping` flag to return the `data_indices` output in `df_downsample()`. Note that, at this point, `df_movingaverage()` still does _not_ return `data_indices`, although the `return_index_mapping` flag remains an input option. This may be addressed in a future bug fix if needed. 
Bug is reported in issue #52. Change would close this issue.
Changes made to `df_downsample` and test code.
=> Reinstate return_index_mapping in df_downsample

flasc/energy_ratio/energy_ratio.py
Yes
Add check for small number of points in block bootstrapping (less than number of blocks) and in that case revert to using each point as block
=> catch case of small number of points

examples/raw_data_processing/a_03_check_sensor_stuck_faults.py, flasc/turbine_analysis/find_sensor_faults.py
This is a very simple PR that moves some things from `examples/raw_data_processing/a_03_check_sensor_stuck_faults.py` to the internal FLASC workings. This cleans up that step a lot. I'm also doing this in preparation for #48.
=> Simplify how we do sensor stuck fault filtering

flasc/energy_ratio/energy_ratio_wd_bias_estimation.py, flasc/turbine_analysis/__init__.py, flasc/turbine_analysis/northing_offset.py, flasc/turbine_analysis/ws_pow_filtering.py
Migrate certain functions that were only defined in example scripts into core FLASC functionality. This simplifies traditional usage of raw data processing scripts and makes for a generally cleaner code. See the examples in the separate repository flasc_cookiecutter_template.
=> Migrate certain functions that were only defined in example scripts into core FLASC functionality

examples/layout/turbine_dependencies.py, flasc/floris_tools.py, tests/floris_tools_test.py
Ready for review and merge.
New functionality added to floris_tools.py to compute which turbines impact and depend on a specified turbine, based on their variations in power predicted by FLORIS.
Tasks:
=> Code for determining which turbines impact the power of a given turbine

examples/energy_ratio/energy_ratio_vs_wd_for_multiple_dfs.py, examples/energy_ratio/energy_ratio_vs_wd_for_single_df.py, flasc/energy_ratio/energy_ratio.py, flasc/energy_ratio/energy_ratio_suite.py, flasc/energy_ratio/energy_ratio_visualization.py, requirements.txt, setup.py
This PR adds two useful functionalities to the energy ratio plotting library:
1. The possibility for polar plots. This is based on an article by K. Gunn, "Improvements to the Eddy Viscosity Wind Turbine Wake Model", where the power ratios are plotted over a polar coordinate system.
2. The plotting of the wind speed bins in the energy ratio bin plots. In the current plots, all wind speed bin counts are thrown on a single pile and then plotted. It would be extremely insightful to also see the wind speed distribution within each energy ratio. We do this now. This immediately makes the bottom plot better represent the actual wind conditions.
Combining (1) and (2) turns the bin count plot into a proper wind rose plot. Here's an example from the …
=> Feature: Energy ratio polar plots and wind speed distributions

flasc/energy_ratio/energy_ratio_visualization.py
Ready to be merged
Had a small issue after the polar plotting pull request, a case I was running specified color to energy ratio plots via simple characters like 'k' or 'r', adding the .to_rgb command I think is harmless if already rgb, but converts to a tuple if supplied a character, and this avoids an error when this line in energy_ratio_visualization.py is run:
```
bar_color = colors[ii] + alpha_array[wsii] * (1.0 - np.array(colors[ii]))
```
Since you can't subtract a string from a float
=> Add conversion from char to rgb

examples/energy_ratio/wake_steering_example.py, flasc/visualization.py
Yes, maybe we can delete demo code after you approve and before merging
data_plot was a function I'd found useful in the past for having an on hand way to represent noisy SCADA data (typical example might be achieved offset).  It exists in a pretty out-dated version in FLORIS, so I've added this updated version to FLASC, and will submit another pull request to FLORIS to remove the outdate code
visualization.py
=> Add data plot to visualization

flasc/floris_tools.py, tests/floris_tools_test.py
This feature adds a function to merge multiple FlorisInterface objects into a single object.
N/A.
`floris_tools`
This is a simple function that merges multiple FlorisInterface objects over their turbines. It does not merge wake properties or solver settings. This is helpful when wind farms are split over multiple sections with different turbine definitions, and when modeling neighboring wind farms.
See the unit tests.
=> Feature: merge FlorisInterface objects

flasc/floris_tools.py, requirements.txt, setup.py
Small pull request to raise the requirement of FLORIS up to 3.4.  I had thought this would require updating the example input yamls but with the exception of smarteole examples, these are anyway using the turbine_library input so don't need an update seperately
=> Update floris requirements to 3.4

.github/workflows/python-publish.yml, README.rst, pyproject.toml, setup.py
Adds PyPI integration so that FLASC becomes pip installable without having to clone the repository from GitHub.
Issue #49.
Code deployment.
I have followed the style of FLORIS in the `pyproject.toml` and `python-publish.yml` files.
See my test deployment on the PyPI testing environment, https://test.pypi.org/project/flasc/1.4/. I bumped this to version 1.4 because I made a mistake when uploading 1.3, and you cannot upload the code for the same version number more than once.
**Steps remaining**
```
python3 -m pip install --upgrade build
python3 -m build
python3 -m pip install --upgrade twine
python3 -m twine upload …
```
=> Feature: Add PyPI integration

flasc/turbine_analysis/ws_pow_filtering.py
This PR **is ready** to be merged.
Adds the option to plot the FLORIS power curve in the mean power curve plots.
N/A
`ws_pow_curve_filtering`
This makes it easy to compare the farm-averaged SCADA-based turbine power curve with the one predicted by FLORIS.
N/A
=> Feature: Add floris turbine power curve option in mean ws-power-curve plot

flasc/dataframe_operations/dataframe_filtering.py, flasc/dataframe_operations/dataframe_manipulations.py, flasc/energy_ratio/energy_ratio_visualization.py, flasc/energy_ratio/energy_ratio_wd_bias_estimation.py, flasc/optimization.py, flasc/turbine_analysis/ws_pow_filtering.py, flasc/utilities.py, requirements.txt, setup.py
This PR is not yet ready to be merged.
Various bug fixes throughout the code.
I found various issues running FLASC for wind farm SCADA analyses.
Various
=> Bug fix: various small corrections

flasc/dataframe_operations/dataframe_manipulations.py
This PR **is ready** to be merged.
This fixes a bug in which the relative distance between turbines is not properly calculated when assigning reference values by the closest `N` number of turbines.
N/A
Dataframe manipulations.
N/A
N/A
=> Bug fix: properly assign reference turbine location in calculating closest subset of turbines

flasc/energy_ratio/energy_ratio.py, flasc/energy_ratio/energy_ratio_input.py, flasc/energy_ratio/energy_ratio_output.py, flasc/energy_ratio/energy_ratio_utilities.py, tests/energy_ratio_test.py
Ready to be merged (maybe can delete some commented out lines)
This pull request address Issue #119 , where we inadvertently changed nan filtering from an "Any" to an "All" in the conversion of energy ratio from pandas to polars.  This pull requests fixes the convention back, and adds a test to confirm the expected behavior (and check going forward)
#119
energy_ratio.py
energy_ratio_output.py
energy_ratio_utiltities.py
energy_ratio_test.py
=> Change nan behavior

.gitignore, examples_artificial_data/03_energy_ratio/05_estimate_heterogeneity_from_energy_ratios.py, flasc/energy_ratio/energy_ratio_heterogeneity_mapper.py
This PR is ready to be merged.
This PR adds a separate class for the heterogeneity estimation process, including automatic conversion to FLORIS' `het_map` variable and various visualizations.
N/A
Energy ratio class.
This class is useful for quickly deriving the heterogeneous inflow profiles over all wind directions and formatting it to a FLORIS-compatible format. The class allows you to directly output the heterogeneity profiles to a FLORIS-compatible format so that it can be used in the `het_map` variable. Note that this function linearly extends the measured heterogeneous wind speeds along the wind direction:
The …
=> Feature: Heterogeneity estimator class

examples_artificial_data/00_setup_floris_model/04_geometric_dependencies.py, flasc/floris_tools.py
This PR is ready to be merged, but may require examples.
This function, through very simplified geometry (linear wake expansion, not modeling deficit), identifies which turbines are impacting a set of "turbines of interest". This can be helpful when you are trying to identify which neighboring wind farms affect your farm of interest for a particular wind direction. This function runs in a matter of seconds, vs. the current function which runs FLORIS simulations and can take hours for large farms. At times, this reduction can cut down the size of your FLORIS model by more than 50% and thereby give you massive speed-ups.
N/A
FLORIS tools.
N/A …
=> Feature: Identify impacting turbines geometrically and reduce FLORIS accordingly

flasc/raw_data_handling/sqldatabase_management.py
Correcting sqldatabase to use convention that functions inputs/outputs should be pandas, even in polars used internally.
I don't believe this is a typically used module so doing a quick merge
=> Apply pandas con to sql

flasc/analysis/energy_ratio_heterogeneity_mapper.py
This quick bugfix is meant to address Issue #171 by catching a certain qhull error when using the lin interpolator and falling back to 100% NN interpolator (which is already used to plug nans).  @Bartdoekemeijer  just wanted to flag for you but this will probably be a done deal when you see it...
=> bug fix in plot_layout

setup.py
Update the dependency to coloredlogs to 15 for consistency with FLORIS
#200
=> Update coloredlogs requirement for FLORIS consistency

docs/installation.md
The [installation page of the docs](https://nrel.github.io/flasc/installation.html) incorrectly states that FLASC must be cloned and installed locally. This PR fixes that and describes installation from PyPI.
=> Update docs to describe PyPI installation.

flasc/flasc_dataframe.py, tests/flasc_dataframe_test.py
This pull request adds in the conversions from flasc format to user format, and relavent testing.  
Converts from flasc format to supported wide and long user formats and adds additional tests.
Remaining question: Do we want any dedicated documentation of these conversions?
=> Add dataframe conversions to flascdataframe

setup.py
pyproj currently is given as a requirement, but is not used in the code.  This is a little inconvenient because of issues connecting to package mangement:
https://github.com/astral-sh/uv/issues/8177
This pull request removes it.
=> Remove pyproj as requirement

flasc/analysis/energy_ratio_input.py, flasc/data_processing/dataframe_manipulations.py, flasc/data_processing/energy_ratio_wd_bias_estimation.py, flasc/data_processing/filtering.py, flasc/data_processing/find_sensor_faults.py, flasc/data_processing/northing_offset.py, flasc/data_processing/time_operations.py, flasc/flasc_dataframe.py, flasc/model_fitting/yaw_pow_fitting.py, flasc/utilities/energy_ratio_utilities.py, flasc/utilities/floris_tools.py, flasc/utilities/optimization.py, flasc/utilities/tuner_utilities.py, flasc/utilities/utilities.py, flasc/yaw_optimizer_visualization.py, tests/df_time_operations_test.py, tests/energy_ratio_test.py, tests/flasc_dataframe_test.py
This PR goes through code and updates type hints and docstrings where pd.Dataframe is called for and adds the option for FlascDataFrame to be used as well to clarify code docs.  
Note code mostly updates existing type hints, but where type hints aren't used updates docstrings.  Getting to uniform type hinting and type hinting style can be a future project
Removes requirements time column is included, as this will necessarily be violated in certain conditions
Add a test that initiating an energy ratio analysis with `FlascDataFrame` is ok
Add. to df_time_operations_test.py some additional testing ensuring matching results when using `FlascDataFrame` as input
=> Finish FlascDataFrame (Paul)

flasc/data_processing/filtering.py
This change adds the observed to a pandas groupby operation in filtering.py.  Since 'ws_xxx' is not a categorical this setting does nothing, but silences the present warning:
```
FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
df_pow_and_ws_bins_subset.groupby(by=f"ws_{ti:03d}")[f"pow_{ti:03d}"].median()
```
Thinking it over, even though observed only applies to categorical values, still setting to `True` seemed more appropriate
=> Add observed keyword

flasc/data_processing/filtering.py
The previous pull request #223 assumed the observed keyword would not have an effect on the computation, and so went for the incoming pandas default value of True, based on my read of:
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html
However, this really did change the behavior, which I now understand is because of the preceding cut line:
```
ws_bin_cuts_subset = [
pd.cut(df[f"ws_{ti:03d}"], bins=self._pw_curve_ws_bins) for ti in turbine_subset
]
```
ws is a categorical in this context.   Therefore reverting back to the current default value made explicit by setting `observed=False`
=> set observed to false

flasc/utilities/tuner_utilities.py
This is a very small fix to the function `replicate_nan_values` which replicates NaN values in columns that are common between two dataframes from one to another.  For some reason this does not work for the time column when it is of type `DateTime64DType`.  However, I can't think of a good reason we need to expect to replicate nans in the time column (this functionality is for marking missing turbine data).  So simply omitting this column avoids the issue.
=> Dont replicate nans in time

.github/workflows/python-publish.yml
Fix the pypthon-publish action to work with pyproject.toml
=> [BUGFIX] Fix pypi action to not use setup.py

.github/workflows/python-publish.yml, pyproject.toml
FLASC v2.1.1 patches the pypi build procedure, which was temporarily broken but undetected in v2.1
[BUGFIX] Fig pypi to not use setup.py #229 
**Full Changelog**: https://github.com/NREL/flasc/compare/v2.1...v2.1.1
NREL checklist:
=> FLASC v2.1.1

.github/workflows/python-publish.yml
Add missing twine install to python-publish workflow
=> add twine to install list

flasc/data_processing/dataframe_manipulations.py, tests/dataframe_manipulations_test.py
This pull request addresses issue #235 by adding functions `set_wd_by_upstream_turbines` and `set_wd_by_upstream_turbines_in_radius` to the `dataframe_manipulations` module. The reason for these functions is that wind directions measured by waked turbines can contain biases due to wake effects. Therefore, it could be advantageous to only use unwaked turbines to estimate the wind direction. These functions first use the average wind direction over all turbines to identify the unwaked turbines. Then the unwaked turbines (or unwaked turbines within the specified radius for `set_wd_by_upstream_turbines_in_radius `) are used to compute the final wind direction signal.
This PR closes issue #235 
**Impacted areas of the …
=> Adding functions to set wind direction by upstream turbines

flasc/flasc_dataframe.py, flasc/utilities/utilities.py, tests/flasc_dataframe_test.py
The current method for counting the number of turbines uses a loop to see when the next turbine doesn't appear.  This created an issue for a current project, where simply counting the number of columns that fit the pattern "pow_###" should provide the equivalent result and avoid the issue.  This PR makes the change and adds a missing back test of the older `get_num_turbines` function.
=> Change how number of turbines is counted

.github/workflows/python-publish.yml, pyproject.toml
FLASC v2.2.1 patches the pypi build procedure, switching from passwords to token per (https://pypi.org/help/#apitoken)
NREL checklist:
=> FLASC v2.2.1

README.md, docs/index.md
Adds information about the WETO software stack to the FLASC README.md and docs landing page.
=> Add WETO stack blurb to readme, docs
